public class Main{
    public static void main(String[]args){
        int a=10,b=0,c;
        int arr[]={1,2,3,4,5};
    
        try{
            c=a/b;
        }
        catch(Exception e){
            System.out.println("Catch block of ArithmeticException");
            System.out.println("Exception here is : "+e.toString());
        }
        try{
            System.out.println(arr[6]);
        }
        catch(Exception e){
            System.out.println("\nCatch block of ArrayIndexOutOfBoundsException");
            System.out.println("Exception here is : "+e.toString());
        }
        
    }
}
